### ISSUE TITLE
Is there a requirements.txt?

### ISSUE THREAD

**Issue by vladd11** [samuelyu2002/pedestrian-traffic-lights#9]
Hi. I have some issues to run training with latest version of Pytorch.
I have no time to fix they, so I wanna just downgrade the version, but I don't know what version I should use.

**Comment by vladd11** [comment]
Like:
```
Traceback (most recent call last):
  File "ImVisible-master/Model/training.py", line 94, in <module>
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Found dtype Double but expected Float
```

**Comment by vladd11** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/27568333/154283436-6c407933-8b58-4ce1-a48f-327fe38d27a2.png)
